# Generated by Django 4.1 on 2022-08-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("karting_grapher", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="documents/")),
            ],
        ),
        migrations.AlterField(
            model_name="karting_data",
            name="file",
            field=models.FileField(upload_to="documents/"),
        ),
    ]
